# Generated by Django 6.1 on 2026-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hotel', 'Hotels & Homestays'), ('restaurant', 'Food & Restaurants'), ('repair', 'Repair & Mechanics'), ('home_service', 'Home Services'), ('healthcare', 'Healthcare'), ('retail', 'Shops & Retail'), ('travel', 'Travel & Transport'), ('beauty', 'Beauty & Personal Care'), ('education', 'Education & Training'), ('professional', 'Professional & Digital Services')], max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
